### ISSUE TITLE
Install fails if stackrox namespace not already created

### ISSUE THREAD

**Issue by max-unity** [stackrox/helm-charts#2]
Install of the sensor fails if the "stackrox" namespace does not already exist on the cluster.

```
helm install sensor ./ --namespace stackrox
Error: create: failed to create: namespaces "stackrox" not found
```

The desired behavior would be to have the namespace created if it does not already exist, as the install procedure is likely to happen on new clusters that don't already have a stackrox component (and thus, the namespace) already.

**Comment by clickboo** [comment]
Thanks for note. Did you run the `setup.sh` script in the scripts folder?  The README in the charts directory has the steps documented.

**Comment by max-unity** [comment]
Yeah I ran `setup.sh`, I am following https://github.com/stackrox/helm-charts/tree/master/3.0.41.3/README.md

It doesn't mention needing to create a stackrox namespace in the prereqs, though, it would be better if this was handled by either Helm or the setup script.

**Comment by max-unity** [comment]
My mistake, it looks like the namespace was created by setup.sh. Looks like it was manually deleted after the setup but before the Helm install, hence the error. Thanks!
